version: '3'
services:
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - 8001:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}

  inventory_management:
    image: inventory_management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}